[features]
seeds = false
skip-lint = false

[programs.localnet]
agentity_registry = "Agnt111111111111111111111111111111111111111"

[programs.devnet]
agentity_registry = "Agnt111111111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/agentity-operator.json"

[scripts]
test = "cargo test"
